const KEY="moneyRuleAppV2";
const VERSION="47.3";
const CATEGORIES=["食費","日用品","水光熱費","交通費","美容","医療関係","娯楽","外食","その他"];
const defaultState={settings:{minimumTakeHome:200000,fixedCosts:150000,savingsTarget:50000,extraAllowancePercent:60,extraSavingsPercent:40},income:250000,bonus:0,expenses:[],plannedExpenses:[],fixedExpenses:[],memory:{expenseCategory:"食費",plannedCategory:"食費",plannedMemo:"",plannedDate:"",fixedCategory:"住居費",fixedMemo:"",fixedDay:""}};
let state;
let sessionExpenseDate="";
const now=new Date();
const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;
try{state=JSON.parse(localStorage.getItem(KEY)||JSON.stringify(defaultState));}catch(e){state=structuredClone(defaultState);}
state.settings={...defaultState.settings,...(state.settings||{})};
state.memory={...defaultState.memory,...(state.memory||{})};
delete state.memory.expenseDate;
state.income=Math.max(0,Number(state.income)||0); state.bonus=Math.max(0,Number(state.bonus)||0);
state.expenses=(Array.isArray(state.expenses)?state.expenses:[]).filter(Boolean).map(e=>({...e,amount:Number(e.amount)||0,date:String(e.date||today),category:String(e.category||"その他"),memo:String(e.memo||""),order:Number.isFinite(Number(e.order))?Number(e.order):Number(e.id)||Date.now()}));
state.plannedExpenses=(Array.isArray(state.plannedExpenses)?state.plannedExpenses:[]).filter(Boolean).map(e=>({...e,id:e.id||Date.now()+Math.random(),amount:Number(e.amount)||0,date:String(e.date||today),category:String(e.category||"その他"),memo:String(e.memo||""),order:Number.isFinite(Number(e.order))?Number(e.order):Number(e.id)||Date.now()}));
state.fixedExpenses=(Array.isArray(state.fixedExpenses)?state.fixedExpenses:[]).filter(Boolean).map(e=>({...e,id:e.id||Date.now()+Math.random(),amount:Number(e.amount)||0,category:String(e.category||"その他"),memo:String(e.memo||""),day:Math.min(31,Math.max(1,Number(e.day)||1)),order:Number.isFinite(Number(e.order))?Number(e.order):Number(e.id)||Date.now(),paidMonths:Array.isArray(e.paidMonths)?e.paidMonths.map(String):[]}));
const $=id=>document.getElementById(id); const yen=n=>"¥"+Math.round(Number(n)||0).toLocaleString("ja-JP");
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function monthKey(date=today){return String(date).slice(0,7);}
function monthExpenses(key=monthKey()){return state.expenses.filter(e=>String(e.date||"").slice(0,7)===key);}
function monthPlannedExpenses(key=monthKey()){return state.plannedExpenses.filter(e=>String(e.date||"").slice(0,7)===key);}
function monthDateLabel(key){const [y,m]=key.split("-");return `${y}/${Number(m)}`;}
function getNumbers(){
  const s=state.settings,totalIncome=state.income+state.bonus,minimum=Math.max(0,Number(s.minimumTakeHome)||0),target=Math.max(0,Number(s.savingsTarget)||0);
  const allowancePct=Math.min(100,Math.max(0,Number(s.extraAllowancePercent)||0)),savingsPct=Math.min(100,Math.max(0,Number(s.extraSavingsPercent)||0));
  const extra=Math.max(0,totalIncome-minimum),allowance=extra*allowancePct/100,extraSavings=extra*savingsPct/100,plannedSavings=target+extraSavings;
  const spendingBudget=Math.max(0,totalIncome-plannedSavings);
  const es=monthExpenses(),planned=monthPlannedExpenses(),spent=es.reduce((a,e)=>a+e.amount,0),plannedAmount=planned.reduce((a,e)=>a+e.amount,0),remaining=spendingBudget-spent-plannedAmount;
  return {s,totalIncome,minimum,target,allowancePct,savingsPct,extra,allowance,extraSavings,plannedSavings,spendingBudget,es,planned,spent,plannedAmount,remaining};
}
function getDayInfo(){const d=new Date(),last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),day=d.getDate();return {day,last,remainingDays:last-day+1};}
function calc(){
  const n=getNumbers(),d=getDayInfo(),daily=Math.max(0,n.remaining)/Math.max(1,d.remainingDays);
  const expectedPct=d.day/d.last*100,pacePct=n.spendingBudget>0?n.spent/n.spendingBudget*100:0,paceDelta=pacePct-expectedPct;
  $("incomeView").textContent=yen(n.totalIncome); $("extraIncome").textContent=yen(n.extra); $("plannedSavings").textContent=yen(n.plannedSavings); $("spendingBudget").textContent=yen(n.spendingBudget);
  $("monthSpent").textContent=yen(n.spent); $("remainingBudget").textContent=yen(n.remaining); $("remainingDaysLabel").textContent=`（残り${d.remainingDays}日）`; $("dailyBudget").textContent=yen(daily); $("plannedExpenseView").textContent=yen(n.plannedAmount);
  $("paceRemainingBudget").textContent=yen(n.remaining); $("paceDailyBudget").textContent=yen(daily); $("paceRemainingDays").textContent=`（残り${d.remainingDays}日）`;
  renderBudgetProgress(n.spendingBudget,n.spent); renderValidation(n); renderForecast(n,d);
  renderFixedExpenses();
  renderCategoryChart(n.es); renderDailyChart(n.es); renderMonthlyChart(); renderSavingsChart();
}
function renderForecast(n,d){const amountEl=$("forecastAmount"),statusEl=$("forecastStatus");if(!amountEl||!statusEl)return;if(!n.spent&& !n.plannedAmount){amountEl.textContent=yen(0);statusEl.textContent="まだ支出データがありません";statusEl.className="forecast-status neutral";return;}const elapsed=Math.max(1,d.day),actualAvg=n.spent/elapsed;const projected=n.spent+actualAvg*Math.max(0,d.last-d.day)+n.plannedAmount;amountEl.textContent=yen(projected);if(projected>n.spendingBudget){statusEl.textContent=`予算を${yen(projected-n.spendingBudget)}超える見込みです`;statusEl.className="forecast-status danger";}else{statusEl.textContent=`予算内に収まる見込みです（余り${yen(n.spendingBudget-projected)}）`;statusEl.className="forecast-status good";}}
function renderValidation(n){const el=$("inputValidation");if(!el)return;const issues=[];if(n.allowancePct+n.savingsPct!==100)issues.push(`超過分の割合が合計${n.allowancePct+n.savingsPct}%です（100%にしてください）`);if(n.plannedSavings>n.totalIncome)issues.push(`貯金予定${yen(n.plannedSavings)}が総収入${yen(n.totalIncome)}を上回っています`);if(n.minimum<n.target)issues.push(`最低限の手取り${yen(n.minimum)}より貯金目標${yen(n.target)}のほうが大きくなっています`);if(!issues.length){el.classList.add("hidden");return;}el.textContent="⚠️ "+issues.join(" / ");el.className="validation-warning";}
function loadSettings(){const s=state.settings;$("minimumTakeHome").value=s.minimumTakeHome;$("savingsTarget").value=s.savingsTarget;$("extraAllowancePercent").value=s.extraAllowancePercent;$("extraSavingsPercent").value=s.extraSavingsPercent;$("income").value=state.income||"";$("bonus").value=state.bonus||"";}
function formatExpenseDate(date){const m=String(date||"").match(/^\d{4}[-\/]([0-9]{1,2})[-\/]([0-9]{1,2})$/);return m?`${String(m[1]).padStart(2,"0")}/${String(m[2]).padStart(2,"0")}`:String(date||"");}
function renderExpenses(){const list=$("expenseList"),es=monthExpenses().slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))||(Number(a.order)||0)-(Number(b.order)||0)||Number(a.id)-Number(b.id));$("expenseTotal").textContent=`合計：${yen(es.reduce((s,e)=>s+e.amount,0))}`;if(!es.length){list.innerHTML='<div class="muted expense-empty">まだ支出はありません。</div>';return;}list.innerHTML=`<table class="expense-table"><thead><tr><th>日付</th><th>メモ</th><th>カテゴリ</th><th class="amount-col">金額</th><th class="action-col"></th></tr></thead><tbody>${es.map(e=>`<tr><td>${escapeHtml(formatExpenseDate(e.date))}</td><td class="memo-cell" data-memo="${e.memo?escapeHtml(e.memo):''}">${e.memo?escapeHtml(e.memo):'<span class="muted">—</span>'}</td><td>${escapeHtml(e.category)}</td><td class="amount-col"><strong>${yen(e.amount)}</strong></td><td class="action-col"><div class="edit-delete-buttons"><button type="button" class="edit-btn" data-edit="${e.id}">編集</button><button type="button" class="delete-btn" data-delete="${e.id}">削除</button></div></td></tr>`).join("")}</tbody></table>`;}
function fixedMonthKey(){return monthKey();}
function fixedDueDate(f,key=fixedMonthKey()){const [y,m]=key.split("-").map(Number);const last=new Date(y,m,0).getDate();const day=Math.min(Math.max(1,Number(f.day)||1),last);return `${y}-${String(m).padStart(2,"0")}-${String(day).padStart(2,"0")}`;}
function fixedPaid(f,key=fixedMonthKey()){return Array.isArray(f.paidMonths)&&f.paidMonths.includes(key);}
function renderFixedExpenses(){const list=$("fixedList"),items=state.fixedExpenses.slice().sort((a,b)=>Number(a.day)-Number(b.day)||(Number(a.order)||0)-(Number(b.order)||0)||Number(a.id)-Number(b.id));$("fixedTotal").textContent=`合計：${yen(items.reduce((s,e)=>s+e.amount,0))}`;if(!items.length){list.innerHTML='<div class="muted expense-empty">固定費は登録されていません。</div>';return;}list.innerHTML=`<table class="expense-table fixed-expense-table"><thead><tr><th>支払日</th><th>メモ</th><th>カテゴリ</th><th class="amount-col">金額</th><th class="action-col"></th></tr></thead><tbody>${items.map(e=>{const paid=fixedPaid(e);return `<tr><td>毎月${Number(e.day)}日</td><td class="memo-cell" data-memo="${e.memo?escapeHtml(e.memo):''}">${e.memo?escapeHtml(e.memo):'<span class="muted">—</span>'}</td><td>${escapeHtml(e.category)}</td><td class="amount-col"><strong>${yen(e.amount)}</strong></td><td class="action-col"><div class="edit-delete-buttons">${paid?`<button type="button" class="fixed-paid" data-unpay-fixed="${e.id}">支払済み</button>`:`<button type="button" class="confirm-btn planned-confirm-btn" data-confirm-fixed="${e.id}">支出に確定</button>`}<button type="button" class="edit-btn" data-edit-fixed="${e.id}">編集</button><button type="button" class="delete-btn" data-delete-fixed="${e.id}">削除</button></div></td></tr>`}).join("")}</tbody></table>`;}
function openFixedEdit(id){const e=state.fixedExpenses.find(x=>String(x.id)===String(id));if(!e)return;$("fixedEditModal").dataset.id=String(id);$("fixedEditAmount").value=e.amount;$("fixedEditCategory").value=e.category;$("fixedEditMemo").value=e.memo||"";$("fixedEditDay").value=e.day;$("fixedEditModal").classList.remove("hidden");}
function closeFixedEdit(){$("fixedEditModal").classList.add("hidden");}
function confirmFixed(id){const e=state.fixedExpenses.find(x=>String(x.id)===String(id));if(!e||fixedPaid(e))return;const key=fixedMonthKey(),date=fixedDueDate(e,key);state.expenses.push({id:Date.now()+Math.random(),amount:e.amount,category:e.category,memo:e.memo||"",date,order:Date.now(),fixedId:e.id,fixedMonth:key});e.paidMonths=Array.isArray(e.paidMonths)?e.paidMonths:[];e.paidMonths.push(key);save();renderFixedExpenses();renderExpenses();calc();}
function unpayFixed(id){const e=state.fixedExpenses.find(x=>String(x.id)===String(id));if(!e)return;const key=fixedMonthKey(),date=fixedDueDate(e,key);let idx=state.expenses.findIndex(x=>String(x.fixedId)===String(e.id)&&String(x.fixedMonth)===String(key));if(idx<0){idx=state.expenses.findIndex(x=>String(x.date||"")===String(date)&&Number(x.amount)===Number(e.amount)&&String(x.category||"")===String(e.category||"")&&String(x.memo||"")===String(e.memo||""));}if(idx>=0)state.expenses.splice(idx,1);e.paidMonths=Array.isArray(e.paidMonths)?e.paidMonths.filter(m=>String(m)!==String(key)):[];save();renderFixedExpenses();renderExpenses();calc();}
function renderPlannedExpenses(){const list=$("plannedList"),es=monthPlannedExpenses().slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))||(Number(a.order)||0)-(Number(b.order)||0)||Number(a.id)-Number(b.id));$("plannedTotal").textContent=`合計：${yen(es.reduce((s,e)=>s+e.amount,0))}`;if(!es.length){list.innerHTML='<div class="muted expense-empty">予定支出はありません。</div>';return;}list.innerHTML=`<table class="expense-table planned-expense-table"><thead><tr><th>予定日</th><th>メモ</th><th>カテゴリ</th><th class="amount-col">金額</th><th class="action-col"></th></tr></thead><tbody>${es.map(e=>`<tr><td>${escapeHtml(formatExpenseDate(e.date))}</td><td class="memo-cell" data-memo="${e.memo?escapeHtml(e.memo):''}">${e.memo?escapeHtml(e.memo):'<span class="muted">—</span>'}</td><td>${escapeHtml(e.category)}</td><td class="amount-col"><strong>${yen(e.amount)}</strong></td><td class="action-col"><div class="edit-delete-buttons"><button type="button" class="confirm-btn" data-confirm-planned="${e.id}">支出に確定</button><button type="button" class="edit-btn" data-edit-planned="${e.id}">編集</button><button type="button" class="delete-btn" data-delete-planned="${e.id}">削除</button></div></td></tr>`).join("")}</tbody></table>`;}
function escapeHtml(str){return String(str).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function rollbackExpenseToPlanned(id){const idx=state.expenses.findIndex(x=>String(x.id)===String(id));if(idx<0)return;const e=state.expenses[idx];state.plannedExpenses.push({id:e.plannedSourceId||Date.now()+Math.random(),amount:Number(e.amount)||0,category:e.category||"その他",memo:e.memo||"",date:e.date||today,order:Number(e.order)||Date.now()});state.expenses.splice(idx,1);save();renderPlannedExpenses();renderExpenses();calc();closeEdit();}
function openEdit(id){const e=state.expenses.find(x=>String(x.id)===String(id));if(!e)return;$("editModal").dataset.id=String(id);$("editAmount").value=e.amount;$("editCategory").value=e.category;$("editMemo").value=e.memo||"";$("editDate").value=e.date;$("editModal").classList.remove("hidden");}
function closeEdit(){$("editModal").classList.add("hidden");}
function moveExpense(id,direction){const e=state.expenses.find(x=>String(x.id)===String(id));if(!e)return;const same=state.expenses.filter(x=>String(x.date||"")===String(e.date||"")).sort((a,b)=>(Number(a.order)||0)-(Number(b.order)||0)||Number(a.id)-Number(b.id));const pos=same.findIndex(x=>String(x.id)===String(id)),target=direction==="up"?pos-1:pos+1;if(pos<0||target<0||target>=same.length)return;const a=same[pos],b=same[target],tmp=Number(a.order)||pos; a.order=Number(b.order)||target; b.order=tmp; save();renderExpenses();calc();openEdit(id);}
function movePlanned(id,direction){const e=state.plannedExpenses.find(x=>String(x.id)===String(id));if(!e)return;const same=state.plannedExpenses.filter(x=>String(x.date||"")===String(e.date||"")).sort((a,b)=>(Number(a.order)||0)-(Number(b.order)||0)||Number(a.id)-Number(b.id));const pos=same.findIndex(x=>String(x.id)===String(id)),target=direction==="up"?pos-1:pos+1;if(pos<0||target<0||target>=same.length)return;const a=same[pos],b=same[target],tmp=Number(a.order)||pos; a.order=Number(b.order)||target; b.order=tmp; save();renderPlannedExpenses();calc();openPlannedEdit(id);}
function moveFixed(id,direction){const e=state.fixedExpenses.find(x=>String(x.id)===String(id));if(!e)return;const same=state.fixedExpenses.filter(x=>Number(x.day)===Number(e.day)).sort((a,b)=>(Number(a.order)||0)-(Number(b.order)||0)||Number(a.id)-Number(b.id));const pos=same.findIndex(x=>String(x.id)===String(id)),target=direction==="up"?pos-1:pos+1;if(pos<0||target<0||target>=same.length)return;const a=same[pos],b=same[target],tmp=Number(a.order)||pos; a.order=Number(b.order)||target; b.order=tmp; save();renderFixedExpenses();openFixedEdit(id);}
function openPlannedEdit(id){const e=state.plannedExpenses.find(x=>String(x.id)===String(id));if(!e)return;$("plannedEditModal").dataset.id=String(id);$("plannedEditAmount").value=e.amount;$("plannedEditCategory").value=e.category;$("plannedEditMemo").value=e.memo||"";$("plannedEditDate").value=e.date;$("plannedEditModal").classList.remove("hidden");}
function closePlannedEdit(){$("plannedEditModal").classList.add("hidden");}
function confirmPlanned(id){const idx=state.plannedExpenses.findIndex(x=>String(x.id)===String(id));if(idx<0)return;const p=state.plannedExpenses[idx];state.expenses.push({id:Date.now()+Math.random(),amount:p.amount,category:p.category,memo:p.memo||"",date:p.date||today,order:Date.now(),plannedSourceId:p.id});state.plannedExpenses.splice(idx,1);save();renderFixedExpenses();renderPlannedExpenses();renderExpenses();calc();}
function calculateAmountExpression(value){const s=String(value??"").trim().replace(/,/g,"");if(!s)return null;if(/^\d+(?:\.\d+)?$/.test(s))return String(Number(s));if(!/^[0-9+\-*/().\s]+$/.test(s))return null;try{const result=Function('"use strict";return ('+s+')')();if(!Number.isFinite(result)||result<0)return null;return String(Math.round(result));}catch(e){return null;}}
function bindAmountCalculator(id){const input=$(id);if(!input)return;input.addEventListener("blur",()=>{const result=calculateAmountExpression(input.value);if(result!==null)input.value=result;});input.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();input.blur();}});}
function rememberExpenseInputs(){state.memory.expenseCategory=$("expenseCategory").value;sessionExpenseDate=$("expenseDate").value||today;save();}
function rememberPlannedInputs(){/* 予定支出の直前入力は記憶しない */}
function restoreInputMemory(){const m=state.memory;$("expenseCategory").value=m.expenseCategory||"食費";sessionExpenseDate=today;$("expenseDate").value=today;$("expenseMemo").value="";$("plannedCategory").value="食費";$("plannedMemo").value="";$("plannedDate").value=today;$("fixedCategory").value="住居費";$("fixedMemo").value="";$("fixedDay").value="";document.querySelectorAll("#categoryQuick button").forEach(b=>b.classList.toggle("selected",b.dataset.category===$("expenseCategory").value));document.querySelectorAll("#fixedCategoryQuick button").forEach(b=>b.classList.toggle("selected",b.dataset.category===$("fixedCategory").value));document.querySelectorAll("#plannedCategoryQuick button").forEach(b=>b.classList.toggle("selected",b.dataset.category===$("plannedCategory").value));}
function renderProgressTimeline(day,last){const track=$("progressTimelineTrack"),marker=$("progressTodayMarker"),labels=$("progressTimelineLabels");if(!track||!marker)return;const ratio=d=>last>1?Math.min(1,Math.max(0,(d-1)/(last-1))):0;const pct=ratio(day)*100;marker.style.left=pct+"%";marker.setAttribute("aria-label",`現在${day}日目`);let currentLabel=$("progressTodayLabel");if(!currentLabel){currentLabel=document.createElement("span");currentLabel.id="progressTodayLabel";currentLabel.className="progress-today-label";track.appendChild(currentLabel);}currentLabel.textContent="Today";currentLabel.style.left=pct+"%";if(labels){const days=[1,10,20,last];labels.innerHTML=days.map((d,i)=>`<span class="timeline-label timeline-label-${i}">${i===3?"月末":d+"日"}</span>`).join("");labels.querySelectorAll(".timeline-label").forEach((el,i)=>{el.style.left=(ratio(days[i])*100)+"%";});}}function renderBudgetProgress(budget,spent){const rawPct=budget>0?spent/budget*100:0;const pct=Math.max(0,rawPct);const displayPct=Number.isFinite(pct)?pct.toFixed(2):"0.00";$("budgetProgressText").textContent=`${yen(spent)} / ${yen(budget)}`;$("budgetProgressBar").style.width=Math.min(100,pct)+"%";$("budgetProgressPercent").textContent=`予算${displayPct}%`;const d=getDayInfo();$("budgetStatus").textContent=budget<=0?"予算を設定してください":spent>budget?`予算を${yen(spent-budget)}オーバーしています`:pct<=d.day/d.last*100+5?"順調なペース　この調子！":"やや速いペース";renderProgressTimeline(d.day,d.last);}
function renderCategoryChart(es){const totals=CATEGORIES.map(c=>({name:c,value:es.filter(e=>e.category===c).reduce((a,e)=>a+e.amount,0)})),total=totals.reduce((a,x)=>a+x.value,0),chart=$("categoryChart"),legend=$("categoryLegend");if(!total){chart.innerHTML='<div class="donut-empty">まだ支出がありません</div>';legend.innerHTML="";return;}let cur=0,stops=[];totals.filter(x=>x.value>0).forEach((x,i)=>{const start=cur;cur+=x.value/total*360;stops.push(`hsl(${i*48},55%,55%) ${start}deg ${cur}deg`);});chart.innerHTML=`<div class="donut" style="background:conic-gradient(${stops.join(",")})"><div class="donut-hole"><b>${yen(total)}</b><span>今月</span></div></div>`;legend.innerHTML=totals.filter(x=>x.value>0).map((x,i)=>`<div class="legend-item"><span class="legend-dot" style="background:hsl(${i*48},55%,55%)"></span><span>${x.name}</span><b>${yen(x.value)}</b><small>${Math.round(x.value/total*100)}%</small></div>`).join("");}
function svgBase(svg){if(!svg)return {line:()=>{},text:()=>{},poly:()=>{},circle:()=>{},rect:()=>{}};svg.innerHTML="";svg.setAttribute("preserveAspectRatio","none");const NS="http://www.w3.org/2000/svg";return{line:(x1,y1,x2,y2,cls="gridline")=>{const el=document.createElementNS(NS,"line");Object.entries({x1,y1,x2,y2}).forEach(([k,v])=>el.setAttribute(k,v));el.setAttribute("class",cls);svg.appendChild(el);},text:(x,y,t,cls="axis-label")=>{const el=document.createElementNS(NS,"text");el.setAttribute("x",x);el.setAttribute("y",y);el.setAttribute("class",cls);el.textContent=t;svg.appendChild(el);},poly:(points,cls="series")=>{const el=document.createElementNS(NS,"polyline");el.setAttribute("points",points);el.setAttribute("class",cls);el.setAttribute("fill","none");svg.appendChild(el);},circle:(cx,cy,r,cls="point")=>{const el=document.createElementNS(NS,"circle");el.setAttribute("cx",cx);el.setAttribute("cy",cy);el.setAttribute("r",r);el.setAttribute("class",cls);svg.appendChild(el);},rect:(x,y,w,h,cls="bar")=>{const el=document.createElementNS(NS,"rect");Object.entries({x,y,width:w,height:h}).forEach(([k,v])=>el.setAttribute(k,v));el.setAttribute("rx","3");el.setAttribute("class",cls);svg.appendChild(el);}};}
function renderDailyChart(es){const svg=$("dailyChart"),g=svgBase(svg),W=700,H=260,pad={l:55,r:20,t:20,b:42},d=new Date(),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),vals=Array.from({length:days},(_,i)=>es.filter(e=>{const ds=String(e.date||"");return ds.slice(0,7)===monthKey()&&Number(ds.slice(8,10))===i+1}).reduce((a,e)=>a+e.amount,0)),max=Math.max(1000,...vals);for(let i=0;i<=4;i++){const y=pad.t+(H-pad.t-pad.b)*i/4;g.line(pad.l,y,W-pad.r,y);g.text(8,y+4,yen(max*(1-i/4)));}const pts=vals.map((v,i)=>`${pad.l+(W-pad.l-pad.r)*(i/Math.max(1,days-1))},${H-pad.b-(H-pad.t-pad.b)*v/max}`).join(" ");g.poly(pts);vals.forEach((v,i)=>{if(v>0)g.circle(pad.l+(W-pad.l-pad.r)*(i/Math.max(1,days-1)),H-pad.b-(H-pad.t-pad.b)*v/max,3,"point")});[1,Math.ceil(days/4),Math.ceil(days/2),Math.ceil(days*3/4),days].forEach(day=>g.text(pad.l+(W-pad.l-pad.r)*((day-1)/Math.max(1,days-1)),H-12,String(day)));$("dailyChartSummary").textContent=`今月合計 ${yen(vals.reduce((a,v)=>a+v,0))}・平均 ${yen(vals.reduce((a,v)=>a+v,0)/days)}/日`;}
function renderMonthlyChart(){const svg=$("monthlyChart"),g=svgBase(svg),W=700,H=260,pad={l:55,r:20,t:20,b:42},now=new Date(),keys=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);keys.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`);}const vals=keys.map(k=>monthExpenses(k).reduce((a,e)=>a+e.amount,0)),max=Math.max(1000,...vals);for(let i=0;i<=4;i++){const y=pad.t+(H-pad.t-pad.b)*i/4;g.line(pad.l,y,W-pad.r,y);g.text(8,y+4,yen(max*(1-i/4)));}const pts=vals.map((v,i)=>`${pad.l+(W-pad.l-pad.r)*(i/Math.max(1,vals.length-1))},${H-pad.b-(H-pad.t-pad.b)*v/max}`).join(" ");g.poly(pts);vals.forEach((v,i)=>{const x=pad.l+(W-pad.l-pad.r)*(i/Math.max(1,vals.length-1)),y=H-pad.b-(H-pad.t-pad.b)*v/max;g.circle(x,y,4,"point");g.text(x,H-12,monthDateLabel(keys[i]),"axis-label center")});$("monthlyChartSummary").textContent=`直近6か月の支出合計 ${yen(vals.reduce((a,v)=>a+v,0))}`;}
function renderSavingsChart(){const svg=$("savingsChart"),g=svgBase(svg),W=700,H=260,pad={l:55,r:20,t:20,b:42},now=new Date(),months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push({key:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`});}const n=getNumbers(),vals=months.map(m=>m.key===monthKey()?n.plannedSavings:0),max=Math.max(1000,...vals),barW=(W-pad.l-pad.r)/vals.length*.62;for(let i=0;i<=4;i++){const y=pad.t+(H-pad.t-pad.b)*i/4;g.line(pad.l,y,W-pad.r,y);g.text(8,y+4,yen(max*(1-i/4)));}vals.forEach((v,i)=>{const x=pad.l+(W-pad.l-pad.r)*(i+.5)/vals.length-barW/2,h=(H-pad.t-pad.b)*v/max;g.rect(x,H-pad.b-h,barW,h,"bar");g.text(x+barW/2,H-12,monthDateLabel(months[i].key),"axis-label center")});$("savingsChartSummary").textContent=`今月の貯金予定 ${yen(vals[vals.length-1])}`;}
$("saveIncome").onclick=()=>{state.income=Math.max(0,Number($("income").value)||0);state.bonus=Math.max(0,Number($("bonus").value)||0);save();calc();};
$("saveSettings").onclick=()=>{const allowance=Math.min(100,Math.max(0,Number($("extraAllowancePercent").value)||0)),savings=Math.min(100,Math.max(0,Number($("extraSavingsPercent").value)||0));state.settings={minimumTakeHome:Math.max(0,Number($("minimumTakeHome").value)||0),savingsTarget:Math.max(0,Number($("savingsTarget").value)||0),extraAllowancePercent:allowance,extraSavingsPercent:savings};save();calc();};
$("addExpense").onclick=()=>{const amount=Number(calculateAmountExpression($("expenseAmount").value));if(!amount||amount<0){alert("金額を入力してください。例：1200+300");return;}state.expenses.push({id:Date.now()+Math.random(),amount,category:$("expenseCategory").value,memo:$("expenseMemo").value.trim(),date:$("expenseDate").value||today,order:Date.now()});rememberExpenseInputs();$("expenseDate").value=sessionExpenseDate||today;$("expenseAmount").value="";$("expenseMemo").value="";save();renderExpenses();calc();};
$("addFixedExpense").onclick=()=>{const amount=Number(calculateAmountExpression($("fixedAmount").value));const day=Math.round(Number($("fixedDay").value)||0);if(!amount||amount<0){alert("金額を入力してください。例：10000+2000");return;}if(day<1||day>31){alert("支払日は1〜31日で入力してください。");return;}state.fixedExpenses.push({id:Date.now()+Math.random(),amount,category:$("fixedCategory").value,memo:$("fixedMemo").value.trim(),day,order:Date.now(),paidMonths:[]});$("fixedAmount").value="";rememberFixedInputs();save();renderFixedExpenses();};
$("fixedList").addEventListener("click",e=>{const c=e.target.closest("[data-confirm-fixed]"),u=e.target.closest("[data-unpay-fixed]"),edit=e.target.closest("[data-edit-fixed]"),del=e.target.closest("[data-delete-fixed]");if(c){confirmFixed(c.dataset.confirmFixed);return;}if(u){unpayFixed(u.dataset.unpayFixed);return;}if(edit){openFixedEdit(edit.dataset.editFixed);return;}if(del){const i=state.fixedExpenses.findIndex(x=>String(x.id)===String(del.dataset.deleteFixed));if(i>=0){if(!confirm("この固定費の登録を削除しますか？過去に確定した支出は削除されません。"))return;state.fixedExpenses.splice(i,1);save();renderFixedExpenses();}}});
$("closeFixedModal").onclick=closeFixedEdit;$("cancelFixedEdit").onclick=closeFixedEdit;$("fixedEditModal").onclick=e=>{if(e.target===$("fixedEditModal"))closeFixedEdit();};
$("moveFixedEditUp").onclick=()=>moveFixed($("fixedEditModal").dataset.id,"up");$("moveFixedEditDown").onclick=()=>moveFixed($("fixedEditModal").dataset.id,"down");
$("saveFixedEdit").onclick=()=>{const id=$("fixedEditModal").dataset.id,e=state.fixedExpenses.find(x=>String(x.id)===String(id)),amount=Number(calculateAmountExpression($("fixedEditAmount").value)),day=Math.round(Number($("fixedEditDay").value)||0);if(!e||!amount){alert("金額を入力してください");return;}if(day<1||day>31){alert("支払日は1〜31日で入力してください。");return;}e.amount=amount;e.category=$("fixedEditCategory").value;e.memo=$("fixedEditMemo").value.trim();e.day=day;save();closeFixedEdit();renderFixedExpenses();};
function rememberFixedInputs(){/* 固定費の直前入力は記憶しない */}
$("addPlannedExpense").onclick=()=>{const amount=Number(calculateAmountExpression($("plannedAmount").value));if(!amount||amount<0){alert("金額を入力してください。例：5000+1000");return;}state.plannedExpenses.push({id:Date.now()+Math.random(),amount,category:$("plannedCategory").value,memo:$("plannedMemo").value.trim(),date:$("plannedDate").value||today,order:Date.now()});rememberPlannedInputs();$("plannedAmount").value="";save();renderPlannedExpenses();calc();};
document.querySelectorAll("[data-entry-tab]").forEach(tab=>tab.addEventListener("click",()=>{const key=tab.dataset.entryTab;document.querySelectorAll("[data-entry-tab]").forEach(t=>{const active=t===tab;t.classList.toggle("active",active);t.setAttribute("aria-selected",active?"true":"false");});document.querySelectorAll("[data-entry-panel]").forEach(panel=>panel.classList.toggle("active",panel.dataset.entryPanel===key));}));function bindCategoryQuick(id,selectId){const wrap=$(id);if(!wrap)return;wrap.addEventListener("click",e=>{const btn=e.target.closest("[data-category]");if(!btn)return;$(selectId).value=btn.dataset.category;wrap.querySelectorAll("button").forEach(b=>b.classList.toggle("selected",b===btn));});}bindCategoryQuick("categoryQuick","expenseCategory");bindCategoryQuick("fixedCategoryQuick","fixedCategory");bindCategoryQuick("plannedCategoryQuick","plannedCategory");
$("expenseCategory").addEventListener("change",rememberExpenseInputs);

$("expenseList").addEventListener("click",e=>{const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]");if(edit){openEdit(edit.dataset.edit);return;}if(del){const i=state.expenses.findIndex(x=>String(x.id)===String(del.dataset.delete));if(i>=0){state.expenses.splice(i,1);save();renderExpenses();calc();}}});
$("plannedList").addEventListener("click",e=>{const c=e.target.closest("[data-confirm-planned]"),edit=e.target.closest("[data-edit-planned]"),del=e.target.closest("[data-delete-planned]");if(c){confirmPlanned(c.dataset.confirmPlanned);return;}if(edit){openPlannedEdit(edit.dataset.editPlanned);return;}if(del){const i=state.plannedExpenses.findIndex(x=>String(x.id)===String(del.dataset.deletePlanned));if(i>=0){state.plannedExpenses.splice(i,1);save();renderPlannedExpenses();calc();}}});
$("closeModal").onclick=closeEdit;$("cancelEdit").onclick=closeEdit;$("editModal").onclick=e=>{if(e.target===$("editModal"))closeEdit();};
$("saveEdit").onclick=()=>{const id=$("editModal").dataset.id,e=state.expenses.find(x=>String(x.id)===String(id)),amount=Number(calculateAmountExpression($("editAmount").value));if(!e||!amount){alert("金額を入力してください");return;}e.amount=amount;e.category=$("editCategory").value;e.memo=$("editMemo").value.trim();e.date=$("editDate").value||today;save();closeEdit();renderExpenses();calc();};
$("moveEditUp").onclick=()=>moveExpense($("editModal").dataset.id,"up");$("moveEditDown").onclick=()=>moveExpense($("editModal").dataset.id,"down");$("rollbackToPlanned").onclick=()=>rollbackExpenseToPlanned($("editModal").dataset.id);
$("closePlannedModal").onclick=closePlannedEdit;$("cancelPlannedEdit").onclick=closePlannedEdit;$("plannedEditModal").onclick=e=>{if(e.target===$("plannedEditModal"))closePlannedEdit();};
$("movePlannedEditUp").onclick=()=>movePlanned($("plannedEditModal").dataset.id,"up");$("movePlannedEditDown").onclick=()=>movePlanned($("plannedEditModal").dataset.id,"down");
$("savePlannedEdit").onclick=()=>{const id=$("plannedEditModal").dataset.id,e=state.plannedExpenses.find(x=>String(x.id)===String(id)),amount=Number(calculateAmountExpression($("plannedEditAmount").value));if(!e||!amount){alert("金額を入力してください");return;}e.amount=amount;e.category=$("plannedEditCategory").value;e.memo=$("plannedEditMemo").value.trim();e.date=$("plannedEditDate").value||today;save();closePlannedEdit();renderPlannedExpenses();calc();};
function exportBackup(){const data={format:"money-rule-backup",version:VERSION,exportedAt:new Date().toISOString(),localStorage:{}};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key&&key.startsWith("moneyRule"))data.localStorage[key]=localStorage.getItem(key);}const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`money-rule-backup-${today.replaceAll("-","")}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);$("backupStatus").textContent="バックアップを書き出しました。";}
function importBackupFile(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data||data.format!=="money-rule-backup"||!data.localStorage||typeof data.localStorage!=="object")throw new Error();if(!confirm("バックアップを読み込むと現在の家計簿データが置き換わります。続行しますか？"))return;Object.keys(data.localStorage).filter(k=>k.startsWith("moneyRule")).forEach(k=>localStorage.setItem(k,String(data.localStorage[k])));location.reload();}catch(e){alert("バックアップファイルを読み込めませんでした。");}};reader.readAsText(file);}
$("exportBackup").onclick=exportBackup;$("importBackupButton").onclick=()=>$("importBackup").click();$("importBackup").addEventListener("change",e=>{importBackupFile(e.target.files?.[0]);e.target.value="";});
const sectionPrefs=JSON.parse(localStorage.getItem("moneyRuleSectionPrefs")||"{}"),statPrefs=JSON.parse(localStorage.getItem("moneyRuleStatPrefs")||"{}");
function applyStatPrefs(){const hidden=statPrefs.income===true;["incomeStat","extraIncomeStat"].forEach(id=>$(id)?.classList.toggle("stat-hidden",hidden));const b=$("incomeRestore")?.querySelector("button");if(b)b.textContent=hidden?"前月の収入を表示":"前月の収入を非表示";}
function applySectionPrefs(){document.querySelectorAll("[data-section-content]").forEach(section=>{const hidden=sectionPrefs[section.dataset.sectionContent]===true;section.querySelectorAll(":scope > *:not(.section-title)").forEach(child=>child.classList.toggle("section-body-hidden",hidden));});document.querySelectorAll(".minus-btn").forEach(btn=>{const hidden=sectionPrefs[btn.dataset.section]===true;btn.textContent=hidden?"＋":"−";});}
function toggleSection(k){sectionPrefs[k]=sectionPrefs[k]!==true;localStorage.setItem("moneyRuleSectionPrefs",JSON.stringify(sectionPrefs));applySectionPrefs();}
function showMemoPopup(cell,event){const text=cell.dataset.memo||"";if(!text)return;const popup=$("memoPopup");if(!popup)return;popup.textContent=text;popup.classList.remove("hidden");const rect=cell.getBoundingClientRect();const margin=8;popup.style.left="0px";popup.style.top="0px";const pw=Math.min(320,window.innerWidth-2*margin);popup.style.maxWidth=pw+"px";const pr=popup.getBoundingClientRect();let left=event.clientX-pr.width/2;left=Math.max(margin,Math.min(window.innerWidth-pr.width-margin,left));let top=rect.top-pr.height-8;if(top<margin)top=Math.min(window.innerHeight-pr.height-margin,rect.bottom+8);popup.style.left=left+"px";popup.style.top=Math.max(margin,top)+"px";clearTimeout(window.__memoPopupTimer);window.__memoPopupTimer=setTimeout(()=>popup.classList.add("hidden"),2000);}
document.addEventListener("click",e=>{const cell=e.target.closest(".memo-cell");if(cell){showMemoPopup(cell,e);return;}if(!e.target.closest("#memoPopup"))$("memoPopup")?.classList.add("hidden");});
document.addEventListener("click",e=>{const b=e.target.closest(".minus-btn");if(b){toggleSection(b.dataset.section);return;}const t=e.target.closest('.stat-toggle-btn[data-stat="income"]');if(t){statPrefs.income=true;localStorage.setItem("moneyRuleStatPrefs",JSON.stringify(statPrefs));applyStatPrefs();}});$("incomeToggle").onclick=()=>{statPrefs.income=!Boolean(statPrefs.income);localStorage.setItem("moneyRuleStatPrefs",JSON.stringify(statPrefs));applyStatPrefs();};
loadSettings();restoreInputMemory();document.querySelectorAll("[data-entry-tab]").forEach((t,i)=>t.setAttribute("aria-selected",i===0?"true":"false"));bindAmountCalculator("expenseAmount");bindAmountCalculator("plannedAmount");bindAmountCalculator("editAmount");bindAmountCalculator("plannedEditAmount");renderFixedExpenses();renderPlannedExpenses();renderExpenses();calc();applySectionPrefs();applyStatPrefs();requestAnimationFrame(()=>{const n=getNumbers();renderCategoryChart(n.es);renderDailyChart(n.es);renderMonthlyChart();renderSavingsChart();});
